
const API = "/api";
let state = {page:"dashboard", innovations:[], selected:1, searchResults:[], reports:[], tk:null, reg:null, risk:null, jurisdiction:localStorage.getItem("ipsakti_jurisdiction")||"India", language:localStorage.getItem("ipsakti_language")||"English"};

const LANGUAGES = ["English","Hindi","Telugu","Kannada","Tamil","Malayalam","Marathi","Bengali","Gujarati","Punjabi","Odia","Assamese","Urdu","Sanskrit","Nepali"];
const COUNTRIES = ["India","United States","European Union","Australia","UAE"];
const navTranslations = {
  English:["Dashboard","Innovation & Classification","IP & Prior-Art","TK & Biodiversity","Regulatory & International","AI Assistant","Risk, Evidence & Action","Reports & Settings"],
  Hindi:["डैशबोर्ड","नवाचार और वर्गीकरण","आईपी और पूर्व कला","पारंपरिक ज्ञान और जैव विविधता","नियामक और अंतरराष्ट्रीय","एआई सहायक","जोखिम, साक्ष्य और कार्य","रिपोर्ट और सेटिंग्स"],
  Telugu:["డ్యాష్‌బోర్డ్","ఆవిష్కరణ & వర్గీకరణ","IP & పూర్వ కళ","సాంప్రదాయ జ్ఞానం & జీవ వైవిధ్యం","నియంత్రణ & అంతర్జాతీయ","AI సహాయకుడు","ప్రమాదం, ఆధారాలు & చర్య","రిపోర్టులు & సెట్టింగ్స్"],
  Kannada:["ಡ್ಯಾಶ್‌ಬೋರ್ಡ್","ಆವಿಷ್ಕಾರ & ವರ್ಗೀಕರಣ","IP & ಪೂರ್ವ ಕಲೆ","ಸಾಂಪ್ರದಾಯಿಕ ಜ್ಞಾನ & ಜೀವ ವೈವಿಧ್ಯ","ನಿಯಂತ್ರಣ & ಅಂತರರಾಷ್ಟ್ರೀಯ","AI ಸಹಾಯಕ","ಅಪಾಯ, ಸಾಕ್ಷ್ಯ & ಕ್ರಮ","ವರದಿಗಳು & ಸೆಟ್ಟಿಂಗ್ಸ್"],
  Tamil:["டாஷ்போர்டு","புதுமை & வகைப்படுத்தல்","IP & முந்தைய கலை","பாரம்பரிய அறிவு & உயிரியல் பல்வகைமை","ஒழுங்குமுறை & சர்வதேசம்","AI உதவியாளர்","ஆபத்து, ஆதாரம் & நடவடிக்கை","அறிக்கைகள் & அமைப்புகள்"],
  Malayalam:["ഡാഷ്ബോർഡ്","ഇന്നൊവേഷൻ & വർഗ്ഗീകരണം","IP & മുൻകല","പരമ്പരാഗത ജ്ഞാനം & ജൈവവൈവിധ്യം","നിയന്ത്രണം & അന്താരാഷ്ട്രം","AI സഹായി","റിസ്ക്, തെളിവ് & നടപടി","റിപ്പോർട്ടുകൾ & ക്രമീകരണങ്ങൾ"],
  Marathi:["डॅशबोर्ड","नवोपक्रम आणि वर्गीकरण","IP आणि पूर्वकला","पारंपरिक ज्ञान आणि जैवविविधता","नियामक आणि आंतरराष्ट्रीय","AI सहाय्यक","जोखीम, पुरावे आणि कृती","अहवाल आणि सेटिंग्ज"],
  Bengali:["ড্যাশবোর্ড","উদ্ভাবন ও শ্রেণিবিন্যাস","IP ও পূর্বকলা","ঐতিহ্যগত জ্ঞান ও জীববৈচিত্র্য","নিয়ন্ত্রক ও আন্তর্জাতিক","AI সহকারী","ঝুঁকি, প্রমাণ ও কার্যক্রম","রিপোর্ট ও সেটিংস"],
  Gujarati:["ડેશબોર્ડ","નવીનતા અને વર્ગીકરણ","IP અને પૂર્વ કલા","પરંપરાગત જ્ઞાન અને જૈવવિવિધતા","નિયમનકારી અને આંતરરાષ્ટ્રીય","AI સહાયક","જોખમ, પુરાવા અને કાર્યવાહી","રિપોર્ટ્સ અને સેટિંગ્સ"],
  Punjabi:["ਡੈਸ਼ਬੋਰਡ","ਨਵੀਨਤਾ ਅਤੇ ਵਰਗੀਕਰਨ","IP ਅਤੇ ਪੂਰਵ ਕਲਾ","ਰਵਾਇਤੀ ਗਿਆਨ ਅਤੇ ਜੈਵ ਵਿਭਿੰਨਤਾ","ਨਿਯਮਕ ਅਤੇ ਅੰਤਰਰਾਸ਼ਟਰੀ","AI ਸਹਾਇਕ","ਜੋਖਮ, ਸਬੂਤ ਅਤੇ ਕਾਰਵਾਈ","ਰਿਪੋਰਟਾਂ ਅਤੇ ਸੈਟਿੰਗਾਂ"],
  Odia:["ଡ୍ୟାସବୋର୍ଡ","ନବୀନତା ଓ ବର୍ଗୀକରଣ","IP ଓ ପୂର୍ବ କଳା","ପାରମ୍ପରିକ ଜ୍ଞାନ ଓ ଜୈବ ବିବିଧତା","ନିୟାମକ ଓ ଆନ୍ତର୍ଜାତୀୟ","AI ସହାୟକ","ବିପଦ, ପ୍ରମାଣ ଓ କାର୍ଯ୍ୟ","ରିପୋର୍ଟ ଓ ସେଟିଂସ୍"],
  Assamese:["ডেশ্বব'ৰ্ড","উদ্ভাৱন আৰু শ্ৰেণীবিভাজন","IP আৰু পূৰ্ব কলা","পৰম্পৰাগত জ্ঞান আৰু জৈৱ বৈচিত্ৰ্য","নিয়ন্ত্ৰণ আৰু আন্তঃৰাষ্ট্ৰীয়","AI সহায়ক","বিপদ, প্ৰমাণ আৰু কাৰ্য","প্ৰতিবেদন আৰু ছেটিংছ"],
  Urdu:["ڈیش بورڈ","اختراع اور درجہ بندی","IP اور سابقہ فن","روایتی علم اور حیاتیاتی تنوع","ضابطہ اور بین الاقوامی","AI معاون","خطرہ، ثبوت اور کارروائی","رپورٹس اور ترتیبات"],
  Sanskrit:["अवलोकन-पटलम्","नवोन्मेषः एवं वर्गीकरणम्","IP एवं पूर्वकला","पारम्परिकज्ञानम् एवं जैवविविधता","नियमनम् एवं अन्तर्राष्ट्रीयम्","AI सहायकः","जोखिमम्, प्रमाणम् एवं कार्यम्","प्रतिवेदनानि एवं विन्यासाः"],
  Nepali:["ड्यासबोर्ड","नवप्रवर्तन र वर्गीकरण","IP र पूर्व कला","परम्परागत ज्ञान र जैव विविधता","नियामक र अन्तर्राष्ट्रिय","AI सहायक","जोखिम, प्रमाण र कार्य","रिपोर्ट र सेटिङहरू"]
};

const UI = {
  English:{Dashboard:'Dashboard', 'Innovation & Classification':'Innovation & Classification','IP & Prior-Art':'IP & Prior-Art','TK & Biodiversity':'TK & Biodiversity','Regulatory & International':'Regulatory & International','AI Assistant':'AI Assistant','Risk, Evidence & Action':'Risk, Evidence & Action','Reports & Settings':'Reports & Settings','New Innovation':'New Innovation','Need Help?':'Need Help?','Talk to our IP Expert':'Talk to our IP Expert','Welcome back, Dr. Ananya! 🌿':"Welcome back, Dr. Ananya! 🌿",'Total Innovations':'Total Innovations','IP Opportunities':'IP Opportunities','Pending Actions':'Pending Actions','Alerts':'Alerts','Risk Summary':'Risk Summary','Recent Innovations':'Recent Innovations','View all':'View all','Top IP Opportunities':'Top IP Opportunities','View All Reports':'View All Reports','View Scheduled Reports':'View Scheduled Reports','Settings':'Settings','Profile & Account':'Profile & Account','Workspace Settings':'Workspace Settings','Notification Preferences':'Notification Preferences','Data & Privacy':'Data & Privacy','Report Preferences':'Report Preferences','System Preferences':'System Preferences','Save changes':'Save changes','Cancel':'Cancel','Generate':'Generate','Completed':'Completed','Status':'Status','Actions':'Actions','Report Name':'Report Name','Type':'Type','Innovation':'Innovation','Generated On':'Generated On','Generated By':'Generated By','All Innovations':'All Innovations','Innovation Name':'Innovation Name','Analyze Innovation':'Analyze Innovation','Quick Actions':'Quick Actions','Suggested Prompts':'Suggested Prompts','Sources':'Sources','Confidence':'Confidence','Information, not legal advice':'Information, not legal advice'},
  Hindi:{Dashboard:'डैशबोर्ड','Innovation & Classification':'नवाचार और वर्गीकरण','IP & Prior-Art':'आईपी और पूर्व कला','TK & Biodiversity':'पारंपरिक ज्ञान और जैव विविधता','Regulatory & International':'नियामक और अंतरराष्ट्रीय','AI Assistant':'एआई सहायक','Risk, Evidence & Action':'जोखिम, साक्ष्य और कार्य','Reports & Settings':'रिपोर्ट और सेटिंग्स','New Innovation':'नया नवाचार','Need Help?':'मदद चाहिए?','Talk to our IP Expert':'हमारे IP विशेषज्ञ से बात करें','Total Innovations':'कुल नवाचार','IP Opportunities':'IP अवसर','Pending Actions':'लंबित कार्य','Alerts':'अलर्ट','Risk Summary':'जोखिम सारांश','Recent Innovations':'हाल के नवाचार','View all':'सभी देखें','Top IP Opportunities':'शीर्ष IP अवसर','View All Reports':'सभी रिपोर्ट देखें','View Scheduled Reports':'निर्धारित रिपोर्ट देखें','Settings':'सेटिंग्स','Profile & Account':'प्रोफ़ाइल और खाता','Workspace Settings':'वर्कस्पेस सेटिंग्स','Notification Preferences':'सूचना प्राथमिकताएँ','Data & Privacy':'डेटा और गोपनीयता','Report Preferences':'रिपोर्ट प्राथमिकताएँ','System Preferences':'सिस्टम प्राथमिकताएँ','Save changes':'परिवर्तन सहेजें','Cancel':'रद्द करें','Generate':'बनाएँ','Completed':'पूर्ण','Status':'स्थिति','Actions':'कार्य','Report Name':'रिपोर्ट नाम','Type':'प्रकार','Innovation':'नवाचार','Generated On':'बनाया गया','Generated By':'बनाने वाला','All Innovations':'सभी नवाचार','Innovation Name':'नवाचार नाम','Analyze Innovation':'नवाचार का विश्लेषण करें','Quick Actions':'त्वरित कार्य','Suggested Prompts':'सुझाए गए प्रश्न','Sources':'स्रोत','Confidence':'विश्वसनीयता','Information, not legal advice':'जानकारी, कानूनी सलाह नहीं'},
  Telugu:{Dashboard:'డ్యాష్‌బోర్డ్','Innovation & Classification':'ఆవిష్కరణ & వర్గీకరణ','IP & Prior-Art':'IP & పూర్వ కళ','TK & Biodiversity':'సాంప్రదాయ జ్ఞానం & జీవ వైవిధ్యం','Regulatory & International':'నియంత్రణ & అంతర్జాతీయ','AI Assistant':'AI సహాయకుడు','Risk, Evidence & Action':'ప్రమాదం, ఆధారాలు & చర్య','Reports & Settings':'రిపోర్టులు & సెట్టింగ్స్','New Innovation':'కొత్త ఆవిష్కరణ','Need Help?':'సహాయం కావాలా?','Talk to our IP Expert':'మా IP నిపుణుడితో మాట్లాడండి','Total Innovations':'మొత్తం ఆవిష్కరణలు','IP Opportunities':'IP అవకాశాలు','Pending Actions':'పెండింగ్ చర్యలు','Alerts':'అలర్ట్లు','Risk Summary':'ప్రమాద సారాంశం','Recent Innovations':'ఇటీవలి ఆవిష్కరణలు','View all':'అన్నీ చూడండి','Top IP Opportunities':'ప్రధాన IP అవకాశాలు','View All Reports':'అన్ని నివేదికలు చూడండి','View Scheduled Reports':'షెడ్యూల్ చేసిన నివేదికలు','Settings':'సెట్టింగ్స్','Profile & Account':'ప్రొఫైల్ & ఖాతా','Workspace Settings':'వర్క్‌స్పేస్ సెట్టింగ్స్','Notification Preferences':'నోటిఫికేషన్ ప్రాధాన్యతలు','Data & Privacy':'డేటా & గోప్యత','Report Preferences':'నివేదిక ప్రాధాన్యతలు','System Preferences':'సిస్టమ్ ప్రాధాన్యతలు','Save changes':'మార్పులను సేవ్ చేయండి','Cancel':'రద్దు','Generate':'సృష్టించండి','Completed':'పూర్తయింది','Status':'స్థితి','Actions':'చర్యలు','Report Name':'నివేదిక పేరు','Type':'రకం','Innovation':'ఆవిష్కరణ','Generated On':'సృష్టించిన తేదీ','Generated By':'సృష్టించిన వారు','All Innovations':'అన్ని ఆవిష్కరణలు','Innovation Name':'ఆవిష్కరణ పేరు','Analyze Innovation':'ఆవిష్కరణను విశ్లేషించండి','Quick Actions':'త్వరిత చర్యలు','Suggested Prompts':'సూచించిన ప్రశ్నలు','Sources':'మూలాలు','Confidence':'నమ్మక స్థాయి','Information, not legal advice':'సమాచారం మాత్రమే, న్యాయ సలహా కాదు'},
  Kannada:{Dashboard:'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್','Innovation & Classification':'ಆವಿಷ್ಕಾರ & ವರ್ಗೀಕರಣ','IP & Prior-Art':'IP & ಪೂರ್ವ ಕಲೆ','TK & Biodiversity':'ಸಾಂಪ್ರದಾಯಿಕ ಜ್ಞಾನ & ಜೀವ ವೈವಿಧ್ಯ','Regulatory & International':'ನಿಯಂತ್ರಣ & ಅಂತರರಾಷ್ಟ್ರೀಯ','AI Assistant':'AI ಸಹಾಯಕ','Risk, Evidence & Action':'ಅಪಾಯ, ಸಾಕ್ಷ್ಯ & ಕ್ರಮ','Reports & Settings':'ವರದಿಗಳು & ಸೆಟ್ಟಿಂಗ್ಸ್','New Innovation':'ಹೊಸ ಆವಿಷ್ಕಾರ','Need Help?':'ಸಹಾಯ ಬೇಕೇ?','Talk to our IP Expert':'ನಮ್ಮ IP ತಜ್ಞರೊಂದಿಗೆ ಮಾತನಾಡಿ','Total Innovations':'ಒಟ್ಟು ಆವಿಷ್ಕಾರಗಳು','IP Opportunities':'IP ಅವಕಾಶಗಳು','Pending Actions':'ಬಾಕಿ ಕ್ರಮಗಳು','Alerts':'ಎಚ್ಚರಿಕೆಗಳು','Risk Summary':'ಅಪಾಯ ಸಾರಾಂಶ','Recent Innovations':'ಇತ್ತೀಚಿನ ಆವಿಷ್ಕಾರಗಳು','View all':'ಎಲ್ಲವನ್ನೂ ನೋಡಿ','Top IP Opportunities':'ಪ್ರಮುಖ IP ಅವಕಾಶಗಳು','View All Reports':'ಎಲ್ಲಾ ವರದಿಗಳನ್ನು ನೋಡಿ','View Scheduled Reports':'ನಿಗದಿತ ವರದಿಗಳನ್ನು ನೋಡಿ','Settings':'ಸೆಟ್ಟಿಂಗ್ಸ್','Profile & Account':'ಪ್ರೊಫೈಲ್ & ಖಾತೆ','Workspace Settings':'ವರ್ಕ್‌ಸ್ಪೇಸ್ ಸೆಟ್ಟಿಂಗ್ಸ್','Notification Preferences':'ಅಧಿಸೂಚನೆ ಆದ್ಯತೆಗಳು','Data & Privacy':'ಡೇಟಾ & ಗೌಪ್ಯತೆ','Report Preferences':'ವರದಿ ಆದ್ಯತೆಗಳು','System Preferences':'ಸಿಸ್ಟಮ್ ಆದ್ಯತೆಗಳು','Save changes':'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ','Cancel':'ರದ್ದುಮಾಡಿ','Generate':'ರಚಿಸಿ','Completed':'ಪೂರ್ಣಗೊಂಡಿದೆ','Status':'ಸ್ಥಿತಿ','Actions':'ಕ್ರಮಗಳು','Report Name':'ವರದಿ ಹೆಸರು','Type':'ಪ್ರಕಾರ','Innovation':'ಆವಿಷ್ಕಾರ','Generated On':'ರಚಿಸಿದ ದಿನಾಂಕ','Generated By':'ರಚಿಸಿದವರು','All Innovations':'ಎಲ್ಲಾ ಆವಿಷ್ಕಾರಗಳು','Innovation Name':'ಆವಿಷ್ಕಾರದ ಹೆಸರು','Analyze Innovation':'ಆವಿಷ್ಕಾರವನ್ನು ವಿಶ್ಲೇಷಿಸಿ','Quick Actions':'ತ್ವರಿತ ಕ್ರಮಗಳು','Suggested Prompts':'ಸೂಚಿಸಿದ ಪ್ರಶ್ನೆಗಳು','Sources':'ಮೂಲಗಳು','Confidence':'ವಿಶ್ವಾಸ','Information, not legal advice':'ಮಾಹಿತಿ ಮಾತ್ರ, ಕಾನೂನು ಸಲಹೆ ಅಲ್ಲ'},
  Tamil:{Dashboard:'டாஷ்போர்டு','Innovation & Classification':'புதுமை & வகைப்படுத்தல்','IP & Prior-Art':'IP & முந்தைய கலை','TK & Biodiversity':'பாரம்பரிய அறிவு & உயிரியல் பல்வகைமை','Regulatory & International':'ஒழுங்குமுறை & சர்வதேசம்','AI Assistant':'AI உதவியாளர்','Risk, Evidence & Action':'ஆபத்து, ஆதாரம் & நடவடிக்கை','Reports & Settings':'அறிக்கைகள் & அமைப்புகள்','New Innovation':'புதிய புதுமை','Need Help?':'உதவி வேண்டுமா?','Talk to our IP Expert':'எங்கள் IP நிபுணரிடம் பேசுங்கள்','Total Innovations':'மொத்த புதுமைகள்','IP Opportunities':'IP வாய்ப்புகள்','Pending Actions':'நிலுவை நடவடிக்கைகள்','Alerts':'எச்சரிக்கைகள்','Risk Summary':'ஆபத்து சுருக்கம்','Recent Innovations':'சமீபத்திய புதுமைகள்','View all':'அனைத்தையும் காண்க','Top IP Opportunities':'முக்கிய IP வாய்ப்புகள்','View All Reports':'அனைத்து அறிக்கைகளையும் காண்க','View Scheduled Reports':'திட்டமிடப்பட்ட அறிக்கைகளைக் காண்க','Settings':'அமைப்புகள்','Profile & Account':'சுயவிவரம் & கணக்கு','Workspace Settings':'பணியிடம் அமைப்புகள்','Notification Preferences':'அறிவிப்பு விருப்பங்கள்','Data & Privacy':'தரவு & தனியுரிமை','Report Preferences':'அறிக்கை விருப்பங்கள்','System Preferences':'கணினி விருப்பங்கள்','Save changes':'மாற்றங்களைச் சேமிக்கவும்','Cancel':'ரத்து','Generate':'உருவாக்கு','Completed':'முடிந்தது','Status':'நிலை','Actions':'செயல்கள்','Report Name':'அறிக்கை பெயர்','Type':'வகை','Innovation':'புதுமை','Generated On':'உருவாக்கிய தேதி','Generated By':'உருவாக்கியவர்','All Innovations':'அனைத்து புதுமைகள்','Innovation Name':'புதுமை பெயர்','Analyze Innovation':'புதுமையை பகுப்பாய்வு செய்','Quick Actions':'விரைவு செயல்கள்','Suggested Prompts':'பரிந்துரைக்கப்பட்ட கேள்விகள்','Sources':'ஆதாரங்கள்','Confidence':'நம்பிக்கை','Information, not legal advice':'தகவல் மட்டுமே, சட்ட ஆலோசனை அல்ல'},
  Malayalam:{Dashboard:'ഡാഷ്ബോർഡ്','Innovation & Classification':'ഇന്നൊവേഷൻ & വർഗ്ഗീകരണം','IP & Prior-Art':'IP & മുൻകല','TK & Biodiversity':'പരമ്പരാഗത ജ്ഞാനം & ജൈവവൈവിധ്യം','Regulatory & International':'നിയന്ത്രണം & അന്താരാഷ്ട്രം','AI Assistant':'AI സഹായി','Risk, Evidence & Action':'റിസ്ക്, തെളിവ് & നടപടി','Reports & Settings':'റിപ്പോർട്ടുകൾ & ക്രമീകരണങ്ങൾ','New Innovation':'പുതിയ ഇന്നൊവേഷൻ','Need Help?':'സഹായം വേണോ?','Talk to our IP Expert':'ഞങ്ങളുടെ IP വിദഗ്ധനുമായി സംസാരിക്കുക','Total Innovations':'മൊത്തം ഇന്നൊവേഷനുകൾ','IP Opportunities':'IP അവസരങ്ങൾ','Pending Actions':'ബാക്കിയുള്ള നടപടികൾ','Alerts':'അലർട്ടുകൾ','Risk Summary':'റിസ്ക് സംഗ്രഹം','Recent Innovations':'സമീപകാല ഇന്നൊവേഷനുകൾ','View all':'എല്ലാം കാണുക','Top IP Opportunities':'മുൻനിര IP അവസരങ്ങൾ','View All Reports':'എല്ലാ റിപ്പോർട്ടുകളും കാണുക','View Scheduled Reports':'ഷെഡ്യൂൾ ചെയ്ത റിപ്പോർട്ടുകൾ കാണുക','Settings':'ക്രമീകരണങ്ങൾ','Profile & Account':'പ്രൊഫൈൽ & അക്കൗണ്ട്','Workspace Settings':'വർക്ക്സ്പേസ് ക്രമീകരണങ്ങൾ','Notification Preferences':'അറിയിപ്പ് മുൻഗണനകൾ','Data & Privacy':'ഡാറ്റ & സ്വകാര്യത','Report Preferences':'റിപ്പോർട്ട് മുൻഗണനകൾ','System Preferences':'സിസ്റ്റം മുൻഗണനകൾ','Save changes':'മാറ്റങ്ങൾ സംരക്ഷിക്കുക','Cancel':'റദ്ദാക്കുക','Generate':'സൃഷ്ടിക്കുക','Completed':'പൂർത്തിയായി','Status':'സ്ഥിതി','Actions':'നടപടികൾ','Report Name':'റിപ്പോർട്ട് പേര്','Type':'തരം','Innovation':'ഇന്നൊവേഷൻ','Generated On':'സൃഷ്ടിച്ച തീയതി','Generated By':'സൃഷ്ടിച്ചത്','All Innovations':'എല്ലാ ഇന്നൊവേഷനുകളും','Innovation Name':'ഇന്നൊവേഷൻ പേര്','Analyze Innovation':'ഇന്നൊവേഷൻ വിശകലനം ചെയ്യുക','Quick Actions':'ദ്രുത നടപടികൾ','Suggested Prompts':'നിർദ്ദേശിച്ച ചോദ്യങ്ങൾ','Sources':'ഉറവിടങ്ങൾ','Confidence':'വിശ്വാസനില','Information, not legal advice':'വിവരങ്ങൾ മാത്രം, നിയമോപദേശം അല്ല'}
};
const commonKeys=Object.keys(UI.English);
function tr(s){return (UI[state.language]&&UI[state.language][s])||UI.English[s]||s}
function localizeRenderedUI(){
  const root=document.getElementById('app'); if(!root)return;
  const map=UI[state.language]||UI.English;
  const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);
  const nodes=[]; while(walker.nextNode()) nodes.push(walker.currentNode);
  nodes.forEach(n=>{let v=n.nodeValue; if(!v||!v.trim())return; let t=v.trim(); if(map[t]) n.nodeValue=v.replace(t,map[t]);});
  root.querySelectorAll('input[placeholder], textarea[placeholder]').forEach(el=>{if(el.dataset.basePlaceholder&&!el.dataset.placeholderTranslated){} const key=el.placeholder; if(map[key]){el.dataset.basePlaceholder=key;el.placeholder=map[key];}});
}

function setLanguage(v){state.language=v;localStorage.setItem("ipsakti_language",v);closeMenus();render();}
function setJurisdiction(v){state.jurisdiction=v;localStorage.setItem("ipsakti_jurisdiction",v);closeMenus();render();toast(`${v} selected`)}

function openProfile(){
  closeMenus();
  const existing=document.getElementById('profileModal');
  if(existing) existing.remove();
  const wrap=document.createElement('div');
  wrap.id='profileModal';
  wrap.className='modal-overlay';
  wrap.innerHTML=`<div class="modal profile-modal" role="dialog" aria-modal="true">
    <div class="modal-head"><div><h2>Profile & Account</h2><p>Manage your local prototype profile.</p></div><button class="modal-close" onclick="document.getElementById('profileModal')?.remove()">×</button></div>
    <div class="profile-card"><div class="avatar large">AV</div><div><h3>Ananya Verma</h3><p>Inventor</p><span class="pill green">Active</span></div></div>
    <div class="profile-grid"><div><label>Name</label><strong>Ananya Verma</strong></div><div><label>Role</label><strong>Inventor</strong></div><div><label>Jurisdiction</label><strong>${esc(state.jurisdiction)}</strong></div><div><label>Language</label><strong>${esc(state.language)}</strong></div></div>
    <div class="modal-actions"><button class="btn" onclick="document.getElementById('profileModal')?.remove();openSetting('Workspace Settings')">Open Settings</button><button class="btn primary" onclick="document.getElementById('profileModal')?.remove()">Done</button></div>
  </div>`;
  document.body.appendChild(wrap);
}

function openNotifications(){
  closeMenus();
  document.getElementById('notificationsModal')?.remove();
  const wrap=document.createElement('div'); wrap.id='notificationsModal'; wrap.className='modal-overlay';
  wrap.innerHTML=`<div class="modal notification-modal" role="dialog" aria-modal="true">
    <div class="modal-head"><div><h2>Notifications</h2><p>3 updates need your attention.</p></div><button class="modal-close" onclick="document.getElementById('notificationsModal')?.remove()">×</button></div>
    <div class="notification-list">
      <div class="notification-item"><span class="notification-dot high"></span><div><strong>New update in Drugs & Cosmetics Rules, 1945</strong><small>Regulatory notification · 20 May 2025</small></div></div>
      <div class="notification-item"><span class="notification-dot medium"></span><div><strong>FSSAI draft guidelines on Ayurveda-Aahar</strong><small>Regulatory update · 18 May 2025</small></div></div>
      <div class="notification-item"><span class="notification-dot low"></span><div><strong>Prior-art review recommended</strong><small>IP assessment · Today</small></div></div>
    </div>
    <div class="modal-actions"><button class="btn" onclick="go('reg');document.getElementById('notificationsModal')?.remove()">Review Regulatory Updates</button><button class="btn primary" onclick="document.getElementById('notificationsModal')?.remove()">Done</button></div>
  </div>`;
  document.body.appendChild(wrap);
}
function openHelp(){
  closeMenus();
  document.getElementById('helpModal')?.remove();
  const wrap=document.createElement('div'); wrap.id='helpModal'; wrap.className='modal-overlay';
  wrap.innerHTML=`<div class="modal help-modal" role="dialog" aria-modal="true">
    <div class="modal-head"><div><h2>Need Help?</h2><p>Get guidance on using IP-SAKTI SAHAYAK.</p></div><button class="modal-close" onclick="document.getElementById('helpModal')?.remove()">×</button></div>
    <div class="help-options">
      <button class="quick" onclick="go('ai');document.getElementById('helpModal')?.remove()">🤖 <div><strong>Ask AI Assistant</strong><span>Ask about patentability, prior art, TK, ABS or regulations.</span></div></button>
      <button class="quick" onclick="go('innovation');document.getElementById('helpModal')?.remove()">🧪 <div><strong>Analyze an Innovation</strong><span>Start a new innovation assessment.</span></div></button>
      <button class="quick" onclick="go('reports');document.getElementById('helpModal')?.remove()">📄 <div><strong>Reports & Settings</strong><span>Generate reports and manage your workspace.</span></div></button>
    </div>
    <div class="footer-note">This prototype provides information and decision-support, not legal advice.</div>
  </div>`;
  document.body.appendChild(wrap);
}

function openSetting(name){
  closeMenus();
  document.getElementById('settingsModal')?.remove();
  const wrap=document.createElement('div'); wrap.id='settingsModal'; wrap.className='modal-overlay';
  const saved=(k,d)=>localStorage.getItem('ipsakti_'+k) ?? d;
  let content='';
  if(name==='Profile & Account') content=`<div class="profile-card"><div class="avatar large">AV</div><div><h3>Ananya Verma</h3><p>Inventor</p><span class="pill green">Active</span></div></div><div class="profile-grid"><div><label>Name</label><strong>Ananya Verma</strong></div><div><label>Role</label><strong>Inventor</strong></div><div><label>Country / Jurisdiction</label><strong>${esc(state.jurisdiction)}</strong></div><div><label>Language</label><strong>${esc(state.language)}</strong></div></div>`;
  else if(name==='Workspace Settings') content=`<div class="settings-form"><label>Default jurisdiction</label><select id="setCountry"><option>India</option><option>United States</option><option>European Union</option><option>Australia</option><option>UAE</option></select><label>Default language</label><select id="setLanguage">${LANGUAGES.map(x=>`<option>${x}</option>`).join('')}</select><label>Dashboard view</label><select id="setView"><option>Detailed</option><option>Compact</option></select></div>`;
  else if(name==='Notification Preferences') content=`<div class="settings-checks"><label><input type="checkbox" id="nReg" ${saved('notify_reg','true')==='true'?'checked':''}> Regulatory alerts</label><label><input type="checkbox" id="nPrior" ${saved('notify_prior','true')==='true'?'checked':''}> Prior-art review alerts</label><label><input type="checkbox" id="nRisk" ${saved('notify_risk','true')==='true'?'checked':''}> Risk and action reminders</label><label><input type="checkbox" id="nReport" ${saved('notify_report','true')==='true'?'checked':''}> Report notifications</label></div>`;
  else if(name==='Data & Privacy') content=`<div class="settings-checks"><label><input type="checkbox" id="audit" ${saved('audit','true')==='true'?'checked':''}> Enable audit logging</label><label><input type="checkbox" id="localOnly" ${saved('local_only','true')==='true'?'checked':''}> Keep prototype data local</label></div><div class="footer-note">This prototype stores workspace data locally. Do not enter confidential or sensitive legal information.</div>`;
  else if(name==='Report Preferences') content=`<div class="settings-form"><label>Default report format</label><select id="reportFormat"><option>Detailed PDF-ready report</option><option>Executive summary</option><option>Evidence-focused report</option></select><label>Include citations</label><select id="citations"><option>Yes</option><option>No</option></select></div>`;
  else content=`<div class="settings-form"><label>Theme</label><select id="theme"><option>System default</option><option>Light</option></select><label>Interface density</label><select id="density"><option>Comfortable</option><option>Compact</option></select><label>AI response style</label><select id="aiStyle"><option>Clear and concise</option><option>Detailed</option></select></div>`;
  wrap.innerHTML=`<div class="modal settings-modal" role="dialog" aria-modal="true"><div class="modal-head"><div><h2>${esc(name)}</h2><p>Manage ${esc(name.toLowerCase())} for this prototype.</p></div><button class="modal-close" onclick="document.getElementById('settingsModal')?.remove()">×</button></div>${content}<div class="modal-actions"><button class="btn" onclick="document.getElementById('settingsModal')?.remove()">Cancel</button><button class="btn primary" onclick="saveSetting('${name.replace(/'/g,"\\'")}')">Save changes</button></div></div>`;
  document.body.appendChild(wrap);
  if(name==='Workspace Settings'){document.getElementById('setCountry').value=state.jurisdiction;document.getElementById('setLanguage').value=state.language;document.getElementById('setView').value=saved('view','Detailed')}
}
function saveSetting(name){
  if(name==='Workspace Settings'){setJurisdiction(document.getElementById('setCountry').value);setLanguage(document.getElementById('setLanguage').value);localStorage.setItem('ipsakti_view',document.getElementById('setView').value);document.getElementById('settingsModal')?.remove();return;}
  if(name==='Notification Preferences'){[['notify_reg','nReg'],['notify_prior','nPrior'],['notify_risk','nRisk'],['notify_report','nReport']].forEach(([k,id])=>localStorage.setItem('ipsakti_'+k,document.getElementById(id).checked));}
  if(name==='Data & Privacy'){localStorage.setItem('ipsakti_audit',document.getElementById('audit').checked);localStorage.setItem('ipsakti_local_only',document.getElementById('localOnly').checked);}
  document.getElementById('settingsModal')?.remove(); toast(name+' saved');
}
function toggleMenu(id){const el=document.getElementById(id);if(!el)return;document.querySelectorAll('.topmenu').forEach(x=>{if(x!==el)x.style.display='none'});el.style.display=el.style.display==='block'?'none':'block'}
function closeMenus(){document.querySelectorAll('.topmenu').forEach(x=>x.style.display='none')}


const nav = [
 ["dashboard","⌂","Dashboard"],
 ["innovation","♧","Innovation & Classification"],
 ["prior","⌕","IP & Prior-Art"],
 ["tk","♧","TK & Biodiversity"],
 ["reg","⚖","Regulatory & International"],
 ["ai","🤖","AI Assistant"],
 ["risk","▥","Risk, Evidence & Action"],
 ["reports","▧","Reports & Settings"]
];

async function api(path, opts={}){
  try{
    const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...opts});
    if(!r.ok) throw new Error(await r.text());
    return await r.json();
  }catch(e){toast("Backend not connected. Start FastAPI first."); throw e}
}
function toast(s){const t=document.getElementById("toast");t.textContent=s;t.style.display="block";setTimeout(()=>t.style.display="none",2500)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function pill(s){let c=s==="High"||s==="Overdue"?"red":s==="Moderate"||s==="Required"?"orange":s==="Low Risk"||s==="Completed"||s==="Verified"||s==="Compliant"?"green":"blue";return `<span class="pill ${c}">${esc(s)}</span>`}

async function load(){
  state.innovations=await api("/innovations");
  if(!state.innovations.find(x=>x.id===state.selected)) state.selected=state.innovations[0]?.id||1;
  if(state.page==="dashboard") await dashboardData();
  render();
}
async function dashboardData(){state.dash=await api("/dashboard")}
function layout(body){
  return `<div class="shell"><aside class="sidebar">
    <div class="brand"><div class="logo">🌿</div><div><b>IP-SAKTI</b><span>SAHAYAK</span><div class="tagline">IP & Regulatory Assistant for Ayurveda</div></div></div>
    <nav class="nav">${nav.map((n,idx)=>`<button class="${state.page===n[0]?"active":""}" onclick="go('${n[0]}')"><span class="ico">${n[1]}</span>${esc(navTranslations[state.language][idx])}</button>`).join("")}</nav>
    <div class="sidebar-bottom"><button class="newbtn" onclick="go('innovation')">＋ New Innovation</button><button class="help" onclick="openHelp()">🎧 <b>Need Help?</b><br><small>Talk to our IP Expert　›</small></button></div>
  </aside><main class="main">
    <header class="topbar"><div class="top-select"><button class="selectbox" onclick="toggleMenu('countryMenu')">🌐　${esc(state.jurisdiction)}　⌄</button><div id="countryMenu" class="topmenu">${COUNTRIES.map(c=>`<button onclick="setJurisdiction('${c}')">${c}</button>`).join('')}</div></div><div class="top-select"><button class="selectbox" onclick="toggleMenu('languageMenu')">◎　${esc(state.language)}　⌄</button><div id="languageMenu" class="topmenu">${LANGUAGES.map(l=>`<button onclick="setLanguage('${l}')">${l}</button>`).join('')}</div></div><button class="iconbtn" title="Notifications" onclick="openNotifications()">♧<sup>3</sup></button><div class="top-select profile-wrap"><button class="profile" onclick="toggleMenu('profileMenu')"><div class="avatar">AV</div><div><b>Ananya Verma</b><small style="display:block;color:#697386">Inventor</small></div>⌄</button><div id="profileMenu" class="topmenu profile-menu"><button onclick="openProfile()">👤　Profile & Account</button><button onclick="openSetting('Workspace Settings')">⚙　Settings</button><button onclick="openSetting('Notification Preferences')">🔔　Notification Preferences</button><button onclick="openSetting('Data & Privacy')">🔒　Privacy & Security</button><button onclick="toast('Sign out is disabled in this local prototype')">↪　Sign Out</button></div></div></header><section class="content">${body}</section>
  </main></div><div id="toast" class="toast"></div>`;
}
function pagehead(title,sub,actions=""){return `<div class="pagehead"><div><h1>${title}</h1><p>${sub}</p></div><div class="head-actions">${actions}</div></div>`}
function current(){return state.innovations.find(x=>x.id===state.selected)||state.innovations[0]}

function dashboard(){
 const d=state.dash||{};
 return pagehead("Welcome back, Dr. Ananya! 🌿","Here's an overview of your innovations, risks, and IP opportunities.",`<button class="btn" onclick="location.href=API+'/export/dashboard.csv'">⇩ Download Dashboard</button>`)+
 `<div class="grid g4">
 ${metric("💡","Total Innovations",d.total_innovations||0,"↑ 2 this month","")}
 ${metric("🎯","IP Opportunities",d.ip_opportunities||0,"↑ 3 this month","bluebg")}
 ${metric("⚖","Pending Actions",String(d.pending_actions||0).padStart(2,"0"),"↓ 1 this week","orangebg")}
 ${metric("⚠","Alerts",String(d.alerts||0).padStart(2,"0"),"View all alerts","redbg")}
 </div>
 <div class="grid g3" style="margin-top:18px">
 <div class="card"><div class="section-title"><h3>Risk Summary</h3></div><div style="position:relative"><div class="donut"></div><div class="donutlabel">Overall Risk<br><b style="color:#ed7e00">Medium</b></div></div><div class="legend">
 ${[["#ef5a59","IP Risk","20%"],["#f58220","TK Risk","30%"],["#f7bd27","Regulatory Risk","25%"],["#267acb","ABS Risk","15%"],["#68bd5a","International Risk","10%"]].map(x=>`<div><span><i class="dot" style="background:${x[0]}"></i>${x[1]}</span>${x[2]}</div>`).join("")}</div><div class="linkrow" onclick="go('risk')">View Detailed Risk Analysis　›</div></div>
 <div class="card"><div class="section-title"><h3>Recent Innovations</h3><button class="link" onclick="go('innovations')">View all</button></div><div class="list">${(d.recent_innovations||[]).map(i=>`<div class="listrow"><div class="listleft"><div class="mini">🌿</div><div><div class="title">${esc(i.name)}</div><div class="sub">Updated: ${esc(i.updated_at)}　•　${esc(i.category)}</div></div></div>${pill("Completed")}</div>`).join("")}</div><div class="linkrow" onclick="go('innovations')">Go to All Innovations　›</div></div>
 <div class="card"><div class="section-title"><h3>Top IP Opportunities</h3><button class="link" onclick="go('prior')">View all</button></div><div class="list">${[
 ["Novel Formulation (Ashwagandha)","Patent","High"],["Brand Name (Guduchi Syrup)","Trademark","High"],["Kumkumadi Radiance (Recipe)","Trade Secret","Medium"],["Design for Packaging","Design","Medium"],["Bacopa monnieri Extract","Plant Variety","Low"]
 ].map(x=>`<div class="listrow"><div class="listleft"><div class="mini">🌿</div><div><div class="title">${x[0]}</div><div class="sub">${x[1]}</div></div></div>${pill(x[2])}</div>`).join("")}</div><div class="linkrow" onclick="go('prior')">Explore All Opportunities　›</div></div>
 </div>
 <div class="grid g3" style="margin-top:18px">
 <div class="card"><div class="section-title"><h3>Pending Actions</h3><button class="link" onclick="go('risk')">View all</button></div>${(d.pending||[]).slice(0,4).map(a=>`<div class="riskline">📝　${esc(a.title)} <span style="float:right;color:#e33;font-size:12px">${a.due_date?`Due: ${a.due_date}`:""}</span></div>`).join("")}<div class="linkrow" onclick="go('risk')">Go to Action Plan　›</div></div>
 <div class="card"><div class="section-title"><h3>Regulatory Alerts</h3><button class="link" onclick="go('reg')">View all</button></div><div class="quick orange"><div>NEW</div><div><strong>New update in Drugs & Cosmetics Rules, 1945</strong><span>Notification dated 20 May 2025</span></div></div><div style="height:10px"></div><div class="quick orange"><div>!</div><div><strong>FSSAI draft guidelines on Ayurveda-Aahar published</strong><span>Notification dated 18 May 2025</span></div></div></div>
 <div class="card"><div class="section-title"><h3>Quick Start</h3></div><div class="grid g2"><button class="quick" onclick="go('innovation')">🧪 <div><strong>Analyze New Innovation</strong></div></button><button class="quick purple" onclick="go('ai')">🤖 <div><strong>Ask AI Assistant</strong></div></button><button class="quick blue" onclick="go('tk')">📖 <div><strong>Check TKDL Database</strong></div></button><button class="quick orange" onclick="go('prior')">📜 <div><strong>Search Prior Art</strong></div></button></div></div>
 </div><div class="footer-note">Disclaimer: IP-SAKTI Sahayak provides information and decision-support based on available sources. It does not constitute legal or professional advice.</div>`;
}
function metric(icon,title,val,small,bg){return `<div class="card metric"><div class="circle ${bg}">${icon}</div><div><h4>${title}</h4><strong>${val}</strong><small>${small}</small></div></div>`}

function allInnovations(){
 const list=state.innovations||[];
 return pagehead("All Innovations","View your saved innovations and their latest analysis results.",`<button class="btn primary" onclick="go('innovation')">＋ New Innovation</button>`)+
 `<div class="card"><div class="section-title"><h3>${list.length} Innovations</h3><span class="muted">Results available immediately</span></div>
 <div class="innovation-grid">${list.map(i=>`<div class="innovation-card" onclick="state.selected=${Number(i.id)||0};go('innovation')">
   <div class="ic-head"><div class="mini">🌿</div><div><h3>${esc(i.name||"Unnamed Innovation")}</h3><div class="sub">${esc(i.brand||"Proprietary Ayurvedic Product")}</div></div>${pill("Completed")}</div>
   <p>${esc(i.description||"No description provided.")}</p>
   <div class="result-grid">
    <div><small>Classification</small><b>${esc(i.category||"Proprietary Ayurvedic Medicine")}</b></div>
    <div><small>Dosage Form</small><b>${esc(i.dosage_form||"—")}</b></div>
    <div><small>IP Potential</small><b class="good">${esc(i.ip_potential||"High")}</b></div>
    <div><small>Risk</small><b>${esc(i.risk||"Low Risk")}</b></div>
   </div>
   <div class="card-actions"><button class="link" onclick="event.stopPropagation();state.selected=${Number(i.id)||0};go('innovation')">View Analysis ›</button><span class="muted">${esc(i.updated_at||"Recently analyzed")}</span></div>
 </div>`).join("") || `<div class="empty"><h3>No innovations yet</h3><p>Create your first innovation to see its analysis here.</p><button class="btn primary" onclick="go('innovation')">Analyze New Innovation</button></div>`}</div></div>
 <div class="footer-note">✓ Saved innovations show their available classification and risk results immediately. Select any innovation to open its detailed analysis.</div>`;
}

function innovation(){
 const i=current()||{};
 return pagehead("Innovation & Classification","Provide details about your innovation to get AI-powered classification and guidance.",`<button class="btn primary" onclick="saveInnovation()">✦ Analyze Innovation</button>`)+
 `<div class="grid g2"><div class="card"><h3 style="color:#08783f">1. Innovation Details</h3><div class="formgrid">
 <div class="field"><label>Innovation / Product Name *</label><input id="name" value="${esc(i.name||"")}"></div><div class="field"><label>Proprietary / Brand Name (if any)</label><input id="brand" value="${esc(i.brand||"")}"></div>
 <div class="field full"><label>Short Description of Innovation *</label><textarea id="description">${esc(i.description||"")}</textarea></div>
 <div class="field full"><label>2. Ingredients / Resources</label><textarea id="ingredients">${esc(i.ingredients||"Ashwagandha extract, Brahmi, Jatamansi")}</textarea></div>
 <div class="field"><label>3. Traditional Knowledge Involved?</label><select id="tk"><option>Yes</option><option>No</option><option>Not Sure</option></select></div>
 <div class="field"><label>4. Intended Use / Indication *</label><select id="use"><option>Stress relief, Anxiety management, Cognitive support</option><option>Muscle pain relief</option><option>Digestive wellness</option><option>Skin wellness</option><option>General wellness</option></select></div>
 <div class="field"><label>5. Target Population</label><select id="target"><option>Adults (18 years and above)</option><option>Adults</option><option>Children</option><option>General population</option></select></div>
 <div class="field"><label>6. Dosage Form *</label><select id="form"><option>Tablet</option><option>Oil</option><option>Syrup</option><option>Cream</option><option>Capsule</option><option>Churna</option></select></div>
 <div class="field full"><label>7. Any Novel Aspect / Innovation in Formulation or Process?</label><textarea id="novel">${esc(i.novel_aspect||"Combination of standardized extracts in a specific ratio for enhanced effect.")}</textarea></div>
 </div></div>
 <div class="card analysis"><div class="tabs"><button class="tab active">✦ AI Analysis & Classification</button><button class="tab">Summary</button></div>
 <div class="analysisbox"><b>🤖 AI Understanding</b><p id="aiunder">Your innovation is an Ayurvedic proprietary formulation in ${esc(i.dosage_form||"tablet")} dosage form intended for wellness support, containing botanical resources.</p></div>
 <h3>Product / Formulation Classification</h3><div class="rows">${[
 ["System of Medicine","Ayurveda"],["Category",i.category||"Proprietary Ayurvedic Medicine"],["Dosage Form",i.dosage_form||"Tablet"],["Route of Administration","Oral"],["Intended Use Category",i.intended_use||"Wellness / Stress Management"],["Risk Class (India)",i.risk||"Low Risk"]
 ].map(x=>`<div class="row"><b>${x[0]}</b><span>${esc(x[1])}</span></div>`).join("")}</div>
 <h3>Relevant References</h3><div class="list">${["Ayurvedic Formulary of India (AFI), Part-1","Drugs & Cosmetics Rules, 1945 – Schedule T","AYUSH Guidelines on Classical Formulations","WHO Guidelines on Evaluation of Herbal Medicines"].map(x=>`<div class="listrow">▤ ${x}<span>›</span></div>`).join("")}</div>
 <div class="footer-note">ⓘ Please review the AI analysis. You can proceed to the next steps for IP, TK and Regulatory assessment.</div></div></div>`;
}
async function saveInnovation(){
 const payload={name:document.getElementById("name").value,brand:document.getElementById("brand").value,
 description:document.getElementById("description").value,ingredients:document.getElementById("ingredients").value,
 traditional_knowledge:document.getElementById("tk").value,intended_use:document.getElementById("use").value,
 target_population:document.getElementById("target").value,dosage_form:document.getElementById("form").value,novel_aspect:document.getElementById("novel").value};
 if(!payload.name||!payload.description){toast("Please enter the product name and description.");return}
 const r=await api("/innovations",{method:"POST",body:JSON.stringify(payload)});state.selected=r.id;state.innovations.unshift(r);toast("Innovation analyzed and saved to database.");await dashboardData();render();
}

function prior(){
 const i=current()||{};
 return pagehead("IP & Prior-Art","Analyze intellectual property protection options and search prior art to assess novelty and freedom to operate.",`<button class="btn" onclick="historyPage()">◷ Prior-Art Search History</button>`)+
 `<div class="card"><div class="tabs"><button class="tab active">◉ Patent</button><button class="tab">▣ Trademark</button><button class="tab">◎ GI</button><button class="tab">Ⓡ Copyright</button><button class="tab">◉ Design</button><button class="tab">♢ Trade Secret</button><button class="tab">◈ Plant Variety</button></div>
 <div class="grid g2"><div><h3>1. Select IP Type</h3><div class="grid g4">${["Patent","Trademark","GI","Copyright","Design","Trade Secret","Plant Variety"].map((x,n)=>`<button class="card" style="padding:14px;border-color:${n===0?"#159251":"#e0e6e3"};color:${n===0?"#08783f":"#111"}">${x}</button>`).join("")}</div>
 <h3 style="margin-top:20px">2. Prior-Art Search</h3><div class="formgrid"><div class="field full"><label>Search With</label><div><label style="display:inline;margin-right:25px"><input type="radio" checked> Keywords</label><label style="display:inline"><input type="radio"> Text</label></div></div><div class="field"><label>Keywords *</label><textarea id="keywords">${esc((i.ingredients||"Ashwagandha")+" "+(i.intended_use||"stress relief"))}</textarea></div><div class="field"><label>IPC/CPC (Optional)</label><input value="A61K 36/48"></div><div class="field"><label>Authority / Database</label><select><option>All (INPADOC, WIPO, USPTO, EPO, IP India)</option></select></div><div class="field"><label>Publication Year</label><select><option>All Years</option></select></div></div><button class="btn primary" style="float:right;margin-top:10px" onclick="searchPrior()">⌕ Search Prior Art</button></div>
 <div><div class="card"><div class="section-title"><h3>IP Protection Overview</h3><button class="link">View Details</button></div><div class="grid g4">${[["Patent Potential","High"],["Novelty Score","72/100"],["Prior-Art Matches","24"],["Freedom to Operate","Moderate"]].map(x=>`<div style="text-align:center;padding:12px;border:1px solid #e3e8e5;border-radius:8px"><small>${x[0]}</small><strong style="display:block;color:${x[1]==="High"?"#08783f":"#e66f00"};font-size:18px;margin-top:8px">${x[1]}</strong></div>`).join("")}</div><div class="footer-note">✓ Your innovation shows good patent potential. Some similar documents found. Detailed analysis below.</div></div>
 <div class="card" style="margin-top:18px"><h3>Similarity Breakdown</h3><div style="position:relative"><div class="donut"></div><div class="donutlabel"><b>${state.searchResults.length||24}</b><br>Matches</div></div><div class="legend"><div>🔴 High Similarity (≥75%) <b>5 (21%)</b></div><div>🟠 Medium Similarity (50–75%) <b>9 (38%)</b></div><div>🟡 Low Similarity (25–50%) <b>7 (29%)</b></div><div>🟢 Very Low Similarity (&lt;25%) <b>3 (12%)</b></div></div></div></div></div>
 <div class="card" style="margin-top:18px"><div class="section-title"><h3>3. Top Prior-Art Results</h3><button class="link" onclick="searchPrior()">View All Results →</button></div><div style="overflow:auto"><table class="table"><thead><tr><th>#</th><th>Publication / Patent No.</th><th>Title</th><th>Assignee / Applicant</th><th>Pub. Date</th><th>Similarity</th><th>Relevance</th></tr></thead><tbody>${(state.searchResults.length?state.searchResults:[
{"publication":"WO 2021/123456 A1","title":"Ashwagandha root extract composition for stress and anxiety management","applicant":"Natural Remedies Pvt. Ltd.","date":"18 Mar 2021","similarity":82,"relevance":"High"},
{"publication":"IN 2020/1045678 A","title":"Herbal composition comprising Withania somnifera for stress relief","applicant":"AyurGen Labs","date":"22 Dec 2020","similarity":68,"relevance":"High"},
{"publication":"US 2019/0345678 A1","title":"Adaptogenic herbal blend for cognitive support","applicant":"Herbalife LLC","date":"14 Nov 2019","similarity":54,"relevance":"Medium"},
{"publication":"EP 3214567 A1","title":"Combination of Bacopa and Withania for improving memory","applicant":"Phytomed AG","date":"09 Jul 2017","similarity":42,"relevance":"Medium"},
{"publication":"IN 2017/012345 A","title":"Tablet containing Brahmi and Jatamansi extracts","applicant":"Ayurveda Care","date":"19 Apr 2017","similarity":28,"relevance":"Low"}]).map((r,n)=>`<tr><td>${n+1}</td><td>${r.publication}</td><td>${r.title}</td><td>${r.applicant}</td><td>${r.date}</td><td>${pill(r.similarity+"%")}</td><td>${pill(r.relevance)}</td></tr>`).join("")}</tbody></table></div></div>
 <div class="card" style="margin-top:18px"><h3>IP Recommendations</h3>${[["Patent","High potential for patent protection. Consider filing a provisional application.","High Priority"],["Trademark","Brand name availability should be checked.","Medium Priority"],["Trade Secret","Manufacturing process and specific extract ratio can be protected.","High Priority"],["Design","Consider unique packaging design protection.","Low Priority"]].map(x=>`<div class="listrow"><div><b>${x[0]}</b><div class="sub">${x[1]}</div></div>${pill(x[2])}</div>`).join("")}</div>
 <div class="footer-note">Disclaimer: Results are AI-assisted and based on available databases. Please consult an IP expert before taking any decision.</div></div>`;
}
async function searchPrior(){const r=await api("/prior-art/search",{method:"POST",body:JSON.stringify({keywords:document.getElementById("keywords").value,ip_type:"Patent",innovation_id:state.selected})});state.searchResults=r.results;toast(`${r.matches} prior-art records analyzed.`);render()}
async function historyPage(){const h=await api("/search-history");alert(h.length? h.map(x=>`${x.searched_on} — ${x.keywords}`).join("\n"):"No searches yet.");}

function tk(){
 const d=state.tk||{};
 return pagehead("TK & Biodiversity","Traditional Knowledge screening, biological-resource analysis and ABS compliance",`<button class="btn" onclick="downloadText('TK-Biodiversity-Summary.txt',JSON.stringify(state.tk,null,2))">⇩ Download Summary</button>`)+
 `<div class="grid g5">${metric("📖","TK Match Found",d.match_found||"Yes","Moderate Similarity","")}${metric("▣","TKDL Pointer",d.pointer_count||3,"Relevant Entries","purplebg")}${metric("🌿","Biological Resources",d.resources||4,"Detected","")}${metric("🛡","ABS Applicability",d.abs?.applicable||"Yes","View Assessment","bluebg")}${metric("⚠","Overall Biodiversity Risk","Moderate","View Risk Analysis","orangebg")}</div>
 <div class="grid g3" style="margin-top:18px"><div class="card"><h3>Traditional Knowledge (TK) Screening</h3><div class="statline"><b>Similarity Score</b><b>62%</b></div><div class="bar"><i style="width:62%"></i></div><div class="statline"><b>Match Level</b><b>Moderate</b></div>${(d.aspects||[]).map(x=>`<div class="riskline">✓ ${x[0]} <span style="float:right;color:#08783f">${x[1]}</span></div>`).join("")}<button class="btn" style="width:100%;margin-top:12px">View Detailed TK Similarity</button></div>
 <div class="card"><h3>TKDL Pointer Results</h3><table class="table"><thead><tr><th>Entry ID</th><th>Title / Description</th><th>Relevance</th></tr></thead><tbody>${(d.pointers||[]).map(x=>`<tr><td>${x[0]}</td><td>${x[1]}</td><td>${pill(x[2])}</td></tr>`).join("")}</tbody></table><button class="btn" style="width:100%;margin-top:12px">View All TKDL Entries</button></div>
 <div class="card"><h3>Biological Resources Detected</h3>${(d.resources||[]).map(x=>`<div class="listrow"><div class="listleft"><div class="mini">🌿</div><div><b>${x[0]}</b><div class="sub">${x[1]}</div></div></div>${pill(x[2])}</div>`).join("")}<button class="btn" style="width:100%;margin-top:12px">View All Resources</button></div></div>
 <div class="grid g2" style="margin-top:18px"><div class="card"><h3>Access and Benefit Sharing (ABS) Assessment</h3><div class="grid g2"><div><b>ABS Applicability</b><h3 style="color:#08783f">${d.abs?.applicable||"Applicable"}</h3><b>Reason</b><p class="muted">${d.abs?.reason||""}</p></div><div><b>Compliance Requirements</b>${(d.abs?.requirements||[]).map(x=>`<div class="riskline">✓ ${x}<span style="float:right;color:#08783f">Required</span></div>`).join("")}</div></div><button class="btn" style="width:100%;margin-top:12px">View ABS Guidelines</button></div><div class="card"><h3>Biodiversity Risk Analysis</h3>${[["Resource Sustainability Risk","Low"],["Over-exploitation Risk","Medium"],["Legal Compliance Risk","Medium"],["Overall Biodiversity Risk","Moderate"]].map(x=>`<div class="riskline">${x[0]} <span style="float:right">${pill(x[1])}</span></div>`).join("")}<button class="btn" style="width:100%;margin-top:12px">View Risk Details</button></div></div>
 <div class="footer-note">ⓘ Note: This analysis is AI-assisted and based on available public data, TKDL entries and biodiversity databases. For legal compliance, consult relevant authorities and domain experts.</div>`;
}

function reg(){
 const d=state.reg||{};
 return pagehead("Regulatory & International","Regulatory compliance in India and global markets with IP and international frameworks",`<button class="btn" onclick="downloadText('Compliance-Summary.txt',JSON.stringify(state.reg,null,2))">⇩ Download Compliance Summary</button>`)+
 `<div class="tabs"><button class="tab active">Regulatory Compliance (India)</button><button class="tab">International Frameworks & IP</button></div>
 <div class="grid g3"><div class="card"><h3>🌿 AYUSH / Drug Regulation (India)</h3>${[["Regulatory Pathway",d.pathway],["Governing Authority",d.authority],["Key Guidelines",d.guidelines],["Licensing Requirement",d.license],["Safety & Efficacy Data",d.safety],["Documentation",d.documentation],["Compliance Status",d.status]].map(x=>`<div class="row"><b>${x[0]}</b><span>${esc(x[1]||"")}</span></div>`).join("")}<div class="footer-note">ⓘ Your innovation is eligible for further review under the selected Ayurvedic pathway. Ensure claims are supported by applicable standards.</div></div>
 <div class="card"><h3>Compliance Requirements</h3>${(d.requirements||[]).map(x=>`<div class="riskline">${x[0]} <span style="float:right">${pill(x[1])}</span></div>`).join("")}<button class="btn" style="width:100%;margin-top:15px">View All Requirements</button></div>
 <div class="card"><h3>International IP</h3>${[["PCT Filing","Eligible"],["Madrid Protocol (TM)","Applicable"],["Hague Agreement (Design)","Applicable"],["WIPO IP Tools","Explore"]].map(x=>`<div class="riskline">${x[0]} <span style="float:right">${pill(x[1])}</span></div>`).join("")}<h3 style="margin-top:22px">Global Frameworks</h3>${["TRIPS Agreement","CBD (Convention on Biological Diversity)","Nagoya Protocol (ABS)","WIPO Guidelines on TK"].map(x=>`<div class="riskline">${x} <span style="float:right">${pill("Applicable")}</span></div>`).join("")}</div></div>
 <div class="card" style="margin-top:18px"><h3>Country Comparison</h3><div style="overflow:auto"><table class="table"><thead><tr><th>Country / Region</th><th>Regulatory Pathway</th><th>Approval Time</th><th>Key Requirement</th><th>IP Protection</th><th>Market Access</th></tr></thead><tbody>${(d.countries||[]).map(x=>`<tr>${x.map((v,j)=>`<td>${j===0?"🌐 ":""}${v}</td>`).join("")}</tr>`).join("")}</tbody></table></div></div>
 <div class="footer-note">Disclaimer: This module provides general regulatory information and does not constitute legal advice. Please consult relevant authorities or domain experts for specific compliance.</div>`;
}

function ai(){
 const i=current()||{};
 return pagehead("AI Assistant","Your intelligent partner for IP, TK, regulatory and innovation support",`<button class="btn">▣ Assistant Guide</button>`)+
 `<div class="grid g2"><div><div class="card"><h3>Quick Actions</h3>${[["⌕","Check Patentability","Assess novelty & patentability"],["⌕","Find Prior Art","Search patents & literature"],["🌿","ABS Compliance Check","Check access & benefit sharing"],["⚖","Regulatory Pathway","Find applicable regulations"],["▣","Draft Documents","Generate reports & letters"],["▤","Explain a Concept","Get simple explanations"]].map((x,n)=>`<button class="quick ${n%3===1?"blue":n%3===2?"purple":""}" style="width:100%;margin:4px 0;text-align:left" onclick="ask('${x[1]}')">${x[0]} <div><strong>${x[1]}</strong><span>${x[2]}</span></div></button>`).join("")}</div><div class="card" style="margin-top:18px"><h3>Suggested Prompts</h3>${["Is my innovation patentable?","Find similar patents for my idea","What TK records exist for this use?","What regulations apply to herbal oils?","How to comply with ABS in India?"].map(x=>`<div class="riskline" onclick="ask('${x}')">${x}<span>›</span></div>`).join("")}</div></div>
 <div class="card chat"><div class="messages" id="messages"><div class="bubble bot">🤖 <b>Hello Ananya! 👋</b><br><br>I’m your IP-SAKTI AI Assistant. I can help you with patentability, prior art search, TK & biodiversity, regulations, and more. How can I assist you today?</div><div class="bubble user">Is my innovation “${esc(i.name||"HerboRelief Pain Relief Oil")}” likely to be patentable?</div><div class="bubble bot">🟢 <b>Based on the information available in IP-SAKTI:</b><br><br>🟢 TK Similarity Score: Moderate (62%)<br>🟢 Novelty Assessment: Possible – some similar uses found but formulation appears novel.<br>🟢 Prior Art: 3 potentially relevant patents identified.<br>🟢 Patentability Likelihood: <span class="pill orange">Moderate</span><br><br>I recommend conducting a detailed prior art search and reviewing claims with a patent expert.</div></div><div class="composer"><input id="chatInput" placeholder="Ask me anything about IP, TK, regulations, or your innovation..." onkeydown="if(event.key==='Enter')sendChat()"><button class="send" onclick="sendChat()">➤</button></div><small class="muted" style="margin-top:8px">ⓘ AI responses are for informational purposes only and not legal advice.</small></div></div>`;
}
function ask(q){go("ai");setTimeout(()=>{document.getElementById("chatInput").value=q;sendChat()},100)}
async function sendChat(){const input=document.getElementById("chatInput"),q=input.value.trim();if(!q)return;const m=document.getElementById("messages");m.innerHTML+=`<div class="bubble user">${esc(q)}</div>`;input.value="";const r=await api("/ai/chat",{method:"POST",body:JSON.stringify({message:q,language:state.language,jurisdiction:state.jurisdiction})});let cites=(r.citations||[]).map((c,i)=>`<div style="margin-top:8px;padding:8px;border-left:3px solid #08783f;background:#f6fbf8"><b>Source ${i+1}: ${esc(c.title)}</b><div class="sub">${esc(c.source)}</div><small>${esc(c.snippet)}</small></div>`).join("");
 m.innerHTML+=`<div class="bubble bot">🤖 ${esc(r.answer)}<br><br><b>Confidence: ${esc(r.confidence)}%</b>${cites}<br><small class="muted">${r.time} · Information, not legal advice</small></div>`;m.scrollTop=m.scrollHeight}

async function risk(){
 state.risk=state.risk||await api("/risk");const d=state.risk;
 return pagehead("Risk, Evidence & Action","Identify risks, review evidence, and track actions to strengthen your innovation",`<button class="btn" onclick="downloadText('Risk-Report.txt',JSON.stringify(state.risk,null,2))">⇩ Download Risk Report</button>`)+
 `<div class="grid g5">${metric("","Overall Risk Level","Moderate","Score: 58 / 100","orangebg")}${metric("▤","Total Risk Areas",d.total_risk_areas,"High: 3　 Medium: 6　 Low: 3","")}${metric("☑","Open Actions",d.open_actions,"Overdue: "+d.overdue,"bluebg")}${metric("▣","Evidence Items",d.evidence_items,"Verified: "+d.verified,"")}${metric("◔","Mitigation Progress",d.mitigation_progress+"%","", "greenbg")}</div>
 <div class="grid g3" style="margin-top:18px"><div class="card"><div class="section-title"><h3>Risk Assessment</h3></div>${d.risk_areas.map(x=>`<div class="riskline"><b>${x.name}</b><span style="float:right">${pill(x.level)}　${x.score}/100　↗</span></div>`).join("")}<button class="btn" style="width:100%;margin-top:12px">View All Risk Details</button></div>
 <div class="card"><h3>Evidence Overview</h3><div style="position:relative"><div class="donut"></div><div class="donutlabel"><b>${d.evidence_items}</b><br>Total</div></div><div class="legend"><div>🟢 Verified <b>${d.verified} (${Math.round(d.verified/d.evidence_items*100)||0}%)</b></div><div>🔵 Pending Review <b>${d.pending_review} (${100-Math.round(d.verified/d.evidence_items*100)||0}%)</b></div></div><button class="btn" style="width:100%;margin-top:12px">Manage Evidence</button></div>
 <div class="card"><h3>Top Risk Drivers</h3>${[["Similar prior art with overlapping claims","3 relevant patents identified","High"],["Incomplete ABS documentation","Additional information required","Medium"],["Claim scope may lack novelty","Review and refine claim language","Medium"],["Market access in EU requires additional data","THMPD documentation pending","Low"]].map(x=>`<div class="listrow"><div><b>${x[0]}</b><div class="sub">${x[1]}</div></div>${pill(x[2])}</div>`).join("")}<button class="btn" style="width:100%;margin-top:12px">View Risk Analysis Report</button></div></div>
 <div class="grid g2" style="margin-top:18px"><div class="card"><div class="section-title"><h3>Evidence Items</h3><button class="link">View All Evidence →</button></div><table class="table"><thead><tr><th>Evidence Title</th><th>Type</th><th>Status</th><th>Source</th><th>Added On</th></tr></thead><tbody>${["Mahanarayan Taila – Composition Study","Eucalyptus globulus – Anti-inflammatory Data","US20220123456A1","ABS Form – Part A","HerboRelief Oil – Formulation Details"].map((x,n)=>`<tr><td>${x}</td><td>${["Traditional Knowledge","Scientific Literature","Patent Document","ABS Document","Internal Document"][n]}</td><td>${pill(n===2||n===3?"Pending Review":"Verified")}</td><td>${["AYUSH Database","PubMed","USPTO","NBA Portal","User Upload"][n]}</td><td>0${4+n} May 2025</td></tr>`).join("")}</tbody></table><button class="btn" style="width:100%;margin-top:12px">Upload / Add Evidence</button></div>
 <div class="card"><div class="section-title"><h3>Action Plan</h3><button class="link">View All Actions →</button></div><table class="table"><thead><tr><th>Action</th><th>Owner</th><th>Due Date</th><th>Status</th></tr></thead><tbody>${(await api("/actions")).slice(0,5).map(a=>`<tr><td>${esc(a.title)}</td><td>${esc(a.owner)}</td><td>${esc(a.due_date)}</td><td>${pill(a.status)}</td></tr>`).join("")}</tbody></table><button class="btn" style="width:100%;margin-top:12px" onclick="addAction()">Add New Action</button></div></div>
 <div class="footer-note">💡 Regularly review risks and update actions to strengthen your innovation's IP and regulatory position.</div>`;
}
async function addAction(){const title=prompt("Action title:");if(!title)return;await api("/actions",{method:"POST",body:JSON.stringify({innovation_id:state.selected,title,owner:"Ananya Verma",status:"To Do"})});toast("Action added.");render()}

async function reports(){
 const rs=state.reports||await api("/reports");state.reports=rs;
 const types=[["▣","IP Landscape Report","Overview of patents, trends, competitors and technology landscape"],["▧","Prior Art Search Report","Detailed prior art search results with relevant documents"],["🛡","Patentability Report","Comprehensive patentability analysis with novelty, inventive step and risk assessment"],["⚖","Regulatory Compliance Report","Summary of regulatory requirements and compliance status"],["🌿","TK & Biodiversity Report","TK similarity, ABS assessment and biodiversity risk summary"]];
 return pagehead("Reports & Settings","Generate reports and manage your account, preferences and workspace",`<button class="btn" onclick="openScheduledReports()">◷ ${tr("View Scheduled Reports")}</button>`)+
 `<div class="grid g5">${types.map(x=>`<div class="card" style="text-align:center"><div style="font-size:28px">${x[0]}</div><h3>${x[1]}</h3><p class="muted">${x[2]}</p><button class="btn" onclick="genReport('${x[1]}')">⇩ Generate</button></div>`).join("")}</div>
 <div class="card" style="margin-top:18px"><div class="section-title"><h3>Recent Reports</h3><button class="link" onclick="openAllReports()">View All Reports →</button></div><table class="table"><thead><tr><th>Report Name</th><th>Type</th><th>Innovation</th><th>Generated On</th><th>Generated By</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rs.slice(0,8).map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.type)}</td><td>${esc((state.innovations.find(i=>i.id===r.innovation_id)||current()||{}).name||"Innovation")}<br><small>${esc((state.innovations.find(i=>i.id===r.innovation_id)||current()||{}).code||"")}</small></td><td>${r.generated_on}</td><td>${r.generated_by}</td><td>${pill(r.status)}</td><td><button class="link" onclick="downloadReport(${r.id})">⇩</button></td></tr>`).join("")||"<tr><td colspan=7>No reports yet. Generate your first report above.</td></tr>"}</tbody></table></div>
 <div class="card" style="margin-top:18px"><h3>Settings</h3><div class="grid g3">${["Profile & Account","Workspace Settings","Notification Preferences","Data & Privacy","Report Preferences","System Preferences"].map(x=>`<button class="quick" onclick="openSetting('${x}')">⚙ <div><strong>${x}</strong><span>Manage preferences and settings　›</span></div></button>`).join("")}</div></div>
 <div class="footer-note">Need help? Contact support for assistance with your workspace and reports.</div>`;
}

function openScheduledReports(){
  closeMenus(); document.getElementById('scheduledReportsModal')?.remove();
  const w=document.createElement('div'); w.id='scheduledReportsModal'; w.className='modal-overlay';
  w.innerHTML=`<div class="modal settings-modal"><div class="modal-head"><div><h2>${tr('View Scheduled Reports')}</h2><p>Manage automatic report schedules.</p></div><button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button></div><div class="settings-checks"><label><input type="checkbox" checked> Weekly IP Landscape Report</label><label><input type="checkbox" checked> Monthly Regulatory Compliance Report</label><label><input type="checkbox"> Monthly TK & Biodiversity Report</label></div><div class="modal-actions"><button class="btn" onclick="this.closest('.modal-overlay').remove()">${tr('Cancel')}</button><button class="btn primary" onclick="toast('Schedule saved');this.closest('.modal-overlay').remove()">${tr('Save changes')}</button></div></div>`;
  document.body.appendChild(w);
}
function openAllReports(){
  closeMenus(); document.getElementById('allReportsModal')?.remove();
  const rows=(state.reports||[]).map(r=>`<div class="listrow"><div><b>${esc(r.name)}</b><div class="sub">${esc(r.type)} · ${esc(r.generated_on)} · ${esc(r.generated_by)}</div></div><div>${pill(r.status)} <button class="link" onclick="downloadReport(${r.id})">⇩</button></div></div>`).join('')||'<p class="muted">No reports generated yet.</p>';
  const w=document.createElement('div'); w.id='allReportsModal'; w.className='modal-overlay';
  w.innerHTML=`<div class="modal notification-modal"><div class="modal-head"><div><h2>${tr('View All Reports')}</h2><p>All generated reports are available here.</p></div><button class="modal-close" onclick="this.closest('.modal-overlay').remove()">×</button></div><div class="list">${rows}</div><div class="modal-actions"><button class="btn primary" onclick="this.closest('.modal-overlay').remove()">Done</button></div></div>`;
  document.body.appendChild(w);
}

async function genReport(type){const r=await api("/reports/generate",{method:"POST",body:JSON.stringify({innovation_id:state.selected,type})});state.reports.unshift(r);toast("Report generated successfully.");render()}
function downloadReport(id){
  if(!id || id === "undefined" || id === "null"){ toast("Report ID is missing. Please generate the report again."); return; }
  location.href=API+"/reports/download/"+encodeURIComponent(id);
}
function downloadText(name,text){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([text],{type:"text/plain"}));a.download=name;a.click();URL.revokeObjectURL(a.href)}

async function render(){
 const app=document.getElementById("app");let body="";
 if(state.page==="dashboard"){await dashboardData();body=dashboard()}
 else if(state.page==="innovations")body=allInnovations();
 else if(state.page==="innovation")body=innovation()
 else if(state.page==="prior")body=prior()
 else if(state.page==="tk"){state.tk=state.tk||await api("/tk");body=tk()}
 else if(state.page==="reg"){state.reg=state.reg||await api("/regulatory");body=reg()}
 else if(state.page==="ai")body=ai()
 else if(state.page==="risk")body=await risk()
 else if(state.page==="reports")body=await reports()
 app.innerHTML=layout(body); localizeRenderedUI()
}
function go(p){state.page=p;closeMenus();render();window.scrollTo(0,0)}

function handleUnwiredButton(btn){
  const text=(btn.innerText||'').replace(/\s+/g,' ').trim();
  if(!text)return;
  if(text.includes('View All Requirements')){toast('All regulatory requirements are shown in this module.');return}
  if(text.includes('View Detailed TK Similarity')){toast('Detailed TK similarity assessment opened.');return}
  if(text.includes('View All TKDL Entries')){toast('TKDL pointer results are shown above.');return}
  if(text.includes('View All Resources')){toast('All detected biological resources are shown above.');return}
  if(text.includes('View ABS Guidelines')){toast('ABS guidance opened for review.');return}
  if(text.includes('View Risk Details')){go('risk');return}
  if(text.includes('View All Risk Details')){go('risk');return}
  if(text.includes('Manage Evidence')){toast('Evidence management opened.');return}
  if(text.includes('View Risk Analysis Report')){downloadText('Risk-Analysis-Report.txt',JSON.stringify(state.risk||{},null,2));return}
  if(text.includes('Upload / Add Evidence')){toast('Evidence upload is available in the prototype workflow.');return}
  if(text.includes('View All Evidence')){toast('All evidence items are displayed in this section.');return}
  if(text.includes('View All Actions')){go('risk');return}
  if(text.includes('View Scheduled Reports')){toast('Scheduled reports panel opened.');return}
  if(text.includes('View All Reports')){toast('All generated reports are displayed above.');return}
  if(text.includes('Assistant Guide')){toast('Ask about patentability, prior art, TK, ABS or regulations.');return}
  if(text.includes('Regulatory Compliance (India)') || text.includes('International Frameworks')){
    document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');toast(text+' selected');return;
  }
  if(text==='Summary'){document.querySelectorAll('.tabs .tab').forEach(x=>x.classList.remove('active'));btn.classList.add('active');toast('Summary selected');return}
  toast(`${text} selected`);
}

document.addEventListener('click', e=>{
  const b=e.target.closest('button');
  if(b && !b.hasAttribute('onclick') && !b.classList.contains('send')) handleUnwiredButton(b);
  if(!e.target.closest('.top-select')) closeMenus();
});
load().catch(()=>{document.getElementById("app").innerHTML="<div style='padding:40px'>Start the backend first, then refresh.</div>"});
